title: (2021年)最高人民法院关于审理买卖合同纠纷案件适用法律问题的解释 - 合同纠纷法规 - 律法网
url: https://www.055110.com/jj/6/6.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 最高人民法院 民法典合同编通则司法解释 典型案例
kind: case
score: 0.0
text_length: 5266
raw_file: source.html
harvested_at: '2026-08-17 17:28:45'
