title: 指导案例193号：闻巍等侵犯公民个人信息案
url: http://www.sdcourt.gov.cn/ytkfqfy/396214/14727099/index.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 侵犯公民个人信息罪 裁判规则 司法解释 典型案例
kind: case
score: 0.6
text_length: 3019
raw_file: null
harvested_at: '2026-08-17 17:28:47'
