title: 最高法判例丨不能仅以行政协议不违反法律、行政法规的强制性规定为由，认定行政协议行为合法有效-最高法指导-北京市盛廷律师事务所
url: https://shengtinglaw.com/zhiku-xiangqing-10755.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政协议履行与解除 行政诉讼典型案例
kind: case
score: 0.0
text_length: 3709
raw_file: source.html
harvested_at: '2026-08-17 17:29:06'
