title: '[第1584号]蒋某某过失致人重伤案-人民法院能否主动适用认罪认罚从宽制度 - 刑事参考案例 - 律法网'
url: https://www.055110.com/xs/1/28082.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑事诉讼法 认罪认罚从宽制度 典型案例 理论研究
kind: paper
score: 0.19999999999999996
text_length: 3271
raw_file: source.html
harvested_at: '2026-08-17 17:28:57'
