title: "规范涉企行政强制 优化法治化营商环境 最高法发布涉企行政强制典型案例（第一批）\n        --北大法律信息网 -- 法律信息服务平台"
url: https://chinalawinfo.com/News/NewsFullText.aspx?NewsId=134265
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政许可与监管 营商环境法治化 典型行政法案例
kind: paper
score: 0.4
text_length: 7791
raw_file: null
harvested_at: '2026-08-17 17:29:26'
