title: 资料_4101
url: https://star.sse.com.cn/aboutus/publication/actofcourt/law/list/c/10643461/files/1cf3b720574f499e8344d322f98dc6c6.pdf
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 证券虚假陈述民事赔偿 司法解释 典型裁判案例
kind: case
score: 0.19999999999999996
text_length: 9679
raw_file: source.pdf
harvested_at: '2026-08-17 17:28:59'
