title: 渣男！知名男團藝人遭爆性侵三名未成少女　「真實身分」曝光是他 | 娛樂 | 三立新聞網  SETN.COM
url: https://www.setn.com/news/1710354
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 未成年人保护法 侵害未成年人权益 典型案例
kind: case
score: 0.8
text_length: 1144
raw_file: source.html
harvested_at: '2026-08-17 17:29:25'
