title: 关于从国外调取民事或商事证据的公约
url: https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzflty/fltysfxzxggy/201812/t20181225_151473.html
category_id: 07_涉外法治与国际司法
category_name: 涉外法治与仲裁海事专题
query: 国际民商事司法协助 域外送达与取证 典型案例
kind: case
score: 0.0
text_length: 13016
raw_file: null
harvested_at: '2026-08-17 17:30:02'
