title: 變態鬼男下手同居人國小女兒！藉口犒賞工作累　強逼打X槍捧X液 | 社會 | 三立新聞網  SETN.COM
url: https://www.setn.com/news/1886467
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 未成年人保护法 侵害未成年人权益 典型案例
kind: case
score: 1.0
text_length: 1192
raw_file: source.html
harvested_at: '2026-08-17 17:29:23'
