title: 潍坊高密山东友道化学有限公司 “5·27”重大爆炸事故调查报告
url: https://www.wangkanglawyer.com/wp-content/uploads/2026/04/1775559071-%E6%BD%8D%E5%9D%8A%E9%AB%98%E5%AF%86%E5%B1%B1%E4%B8%9C%E5%8F%8B%E9%81%93%E5%8C%96%E5%AD%A6%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B85%C2%B727%E9%87%8D%E5%A4%A7%E7%88%86%E7%82%B8%E4%BA%8B%E6%95%85%E8%B0%83%E6%9F%A5%E6%8A%A5%E5%91%8A.pdf
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 安全生产法 危险化学品安全生产 事故责任典型案例
kind: case
score: 0.4
text_length: 53810
raw_file: source.pdf
harvested_at: '2026-08-17 17:29:33'
