title: 认罪认罚从宽制度适用指南
url: http://ytzy.sdcourt.gov.cn/jnanszqfy/389659/389660/389662/4148590/index.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑事诉讼法 认罪认罚从宽制度 典型案例 理论研究
kind: paper
score: 0.8
text_length: 15189
raw_file: null
harvested_at: '2026-08-17 17:28:49'
