title: 提供股权担保后又声明“保证该股权无质押”是否构成保证担保
url: http://yingke.govgw.com/article/2484.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 最高人民法院 民法典物权编 担保制度司法解释 典型案例
kind: case
score: 0.19999999999999996
text_length: 9151
raw_file: source.html
harvested_at: '2026-08-17 17:28:42'
dir_name: 当事人提供股权担保后又声明“保证该股权无质押，否则自愿赔偿损失”的，是否构成保证担保 - 债务担保纠纷 - 专业领域 - 飞跃-北京债务纠纷律师网
rel_dir: references/01_民商法_民法典与公司法/当事人提供股权担保后又声明“保证该股权无质押，否则自愿赔偿损失”的，是否构成保证担保 - 债务担保纠纷
  - 专业领域 - 飞跃-北京债务纠纷律师网
