title: 中国首例适用法律互惠原则承认外国破产程序案件评析 -  - China
url: https://webiis10.mondaq.com/china/insolvency/1727504/%e4%b8%ad%e5%9b%bd%e9%a6%96%e4%be%8b%e9%80%82%e7%94%a8%e6%b3%95%e5%be%8b%e4%ba%92%e6%83%a0%e5%8e%9f%e5%88%99%e6%89%bf%e8%ae%a4%e5%a4%96%e5%9b%bd%e7%a0%b4%e4%ba%a7%e7%a8%8b%e5%ba%8f%e6%a1%88%e4%bb%b6%e8%af%84%e6%9e%90
category_id: 07_涉外法治与国际司法
category_name: 涉外法治与仲裁海事专题
query: 跨境破产承认与协助 司法实践与典型案例
kind: case
score: 0.8
text_length: 4910
raw_file: source.html
harvested_at: '2026-08-17 17:29:47'
