title: 拼多多暴力抗法被罚15亿 | 天价食品安全罚单|违法|裁量|决定书|知名企业_网易订阅
url: https://www.163.com/dy/article/KQVOB8VC0530W1MT.html
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 电子商务法 平台经营者责任 典型案例分析
kind: case
score: 0.0
text_length: 9139
raw_file: source.html
harvested_at: '2026-08-17 17:29:04'
