title: 最高法院案例：行政机关在诉讼中的应诉答辩行为不属于行政诉讼受案范围——吴某诉龙城区市场监督管理局提供虚假答辩材料违法案_征地拆迁律师
url: https://www.zhongliaolvshi.com/zhongliaoshuofa/3865.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 最高人民法院 行政诉讼 指导性案例 裁判要旨
kind: case
score: 0.19999999999999996
text_length: 3049
raw_file: source.html
harvested_at: '2026-08-17 17:29:13'
