title: 最高法院判例：行政协议“法律上或者事实上不能履行”的认定和处理_中国行政律师网
url: http://bjknxz.com/xzss/41088767838.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政协议履行与解除 行政诉讼典型案例
kind: case
score: 1.0
text_length: 16299
raw_file: source.html
harvested_at: '2026-08-17 17:29:03'
