title: 【全国“百优”文书】江苏法院裁判：《行政处罚法》与具体执法领域的处罚规定的关系及适用——某快餐店诉昆山市监局行政处罚案_淮北市交通运输局
url: https://jtj.huaibei.gov.cn/ztzl/yfxz/fzdt/57862949.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政处罚法 处罚法定 过罚相当 典型案例
kind: case
score: 0.19999999999999996
text_length: 12304
raw_file: source.html
harvested_at: '2026-08-17 17:29:15'
