title: 湖北高院裁判：相对人违约情况下行政机关对行政协议的解除权_中国行政律师网
url: http://bjknxz.com/xzss/40967918148.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政协议履行与解除 行政诉讼典型案例
kind: case
score: 0.8
text_length: 14998
raw_file: source.html
harvested_at: '2026-08-17 17:29:03'
