title: 110 年度台上大字第 5217 號 刑事裁定（違反貪污治罪條例提案予刑事大法庭案）- 2026 大法庭裁定｜法律人 LawPlayer
url: https://lawplayer.com/court/643cddf8e800e5f0b940097a
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑法修正案（十二） 行贿受贿一起查 典型案例
kind: case
score: 0.0
text_length: 11563
raw_file: source.html
harvested_at: '2026-08-17 17:29:11'
