title: 最高法第16批指导性案例第78-80号全文
url: http://jnanhyqfy.sdcourt.gov.cn/jnanhyqfy/375203/755889/1547781/index.html
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 最高人民法院 反垄断与反不正当竞争 典型案例
kind: case
score: 0.8
text_length: 17308
raw_file: null
harvested_at: '2026-08-17 17:28:50'
