title: 法院判例：合同目的无法实现情况下行政协议案件的裁判方式
url: http://lyzy.sdcourt.gov.cn/jnangxqfy/400112/400095/10124100/index.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政协议履行与解除 行政诉讼典型案例
kind: case
score: 0.6
text_length: 13397
raw_file: source.html
harvested_at: '2026-08-17 17:29:04'
