title: 司法院全球資訊網-查詢服務-司法新聞查詢-各法院新聞-最高法院刑事大法庭110年度台上大字第3997號違反貪污治罪條例案件新聞稿（111-刑大10）
url: https://www.judicial.gov.tw/tw/cp-1888-686152-4fcdc-1.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑法修正案（十二） 行贿受贿一起查 典型案例
kind: case
score: 1.0
text_length: 1348
raw_file: source.html
harvested_at: '2026-08-17 17:28:50'
