title: 胡云腾：刑事诉讼法中认罪认罚从宽制度的若干思考_重庆渝万律师事务所
url: https://www.lawyeryw.com/article/fazhililun/20251028_1983.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑事诉讼法 认罪认罚从宽制度 典型案例 理论研究
kind: paper
score: 0.0
text_length: 23028
raw_file: null
harvested_at: '2026-08-17 17:29:09'
