title: 国家纵向治理现代化中的立法变通授权_宪法研究_明德公法网
url: http://www.calaw.cn/article/default.asp?id=15040
category_id: 08_宪法与国家机构
category_name: 宪法与国家治理法治专题
query: 立法法修改 地方立法权限与协同立法 案例研究
kind: paper
score: 0.4
text_length: 20281
raw_file: null
harvested_at: '2026-08-17 17:30:26'
