title: 任喜荣 张伟：论宪法精神作为合宪性审查标准的适用_爱思想
url: https://www.aisixiang.com/data/158590.html
category_id: 08_宪法与国家机构
category_name: 宪法与国家治理法治专题
query: 合宪性审查 宪法解释 司法实践与学术论文
kind: paper
score: 0.8
text_length: 27448
raw_file: source.html
harvested_at: '2026-08-17 17:29:48'
