title: 全國首例職場性侵認定工傷案　百萬年薪女高管穿耻辱衣作戰袍出庭
url: https://www.hk01.com/%E5%A4%A7%E5%9C%8B%E5%B0%8F%E4%BA%8B/60279303/%E5%85%A8%E5%9C%8B%E9%A6%96%E4%BE%8B%E8%81%B7%E5%A0%B4%E6%80%A7%E4%BE%B5%E8%AA%8D%E5%AE%9A%E5%B7%A5%E5%82%B7%E6%A1%88-%E7%99%BE%E8%90%AC%E5%B9%B4%E8%96%AA%E5%A5%B3%E9%AB%98%E7%AE%A1%E7%A9%BF%E8%80%BB%E8%BE%B1%E8%A1%A3%E4%BD%9C%E6%88%B0%E8%A2%8D%E5%87%BA%E5%BA%AD
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 妇女权益保障法 职场性别平等 典型司法案例
kind: case
score: 0.0
text_length: 1836
raw_file: source.html
harvested_at: '2026-08-17 17:29:41'
