title: “债权人有权自行决定实现担保的顺序”的约定能否构成明确约定
url: http://www.iestatetoplaw.com/html/rzdb/1108.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 最高人民法院 民法典物权编 担保制度司法解释 典型案例
kind: case
score: 0.4
text_length: 2477
raw_file: source.html
harvested_at: '2026-08-17 17:28:42'
dir_name: 有关“债权人有权自行决定实现担保的顺序”的约定能否得出已就担保物权的实现顺序与方式作出了明确约定？ 房地产法律专家网
rel_dir: references/01_民商法_民法典与公司法/有关“债权人有权自行决定实现担保的顺序”的约定能否得出已就担保物权的实现顺序与方式作出了明确约定？
  房地产法律专家网
