title: 2021年度中国仲裁司法审查实践观察报告——主题四：承认（认可）和执行域外仲裁裁决制度实践观察 | 仲裁圈
url: https://mp.weixin.qq.com/s/Vur9feLDbZ7xvM1AlQy2IA
category_id: 07_涉外法治与国际司法
category_name: 涉外法治与仲裁海事专题
query: 最高人民法院 涉外商事海事仲裁司法审查 典型案例
kind: case
score: 0.19999999999999996
text_length: 9724
raw_file: source.html
harvested_at: '2026-08-17 17:29:47'
