title: 【最高院判例】农村土地承包经营权纠纷与土地权属纠纷的区别_中国土地律师网
url: http://www.bjkntd.com/tudiquanshu/38090428867.html
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 乡村振兴促进法 农村土地承包经营 典型纠纷案例
kind: case
score: 1.0
text_length: 2619
raw_file: source.html
harvested_at: '2026-08-17 17:29:01'
