title: "主权豁免的中国立场\n        - - 法学在线 - 北大法律信息网"
url: https://article.chinalawinfo.com/ArticleFullText.aspx?ArticleId=94477
category_id: 07_涉外法治与国际司法
category_name: 涉外法治与仲裁海事专题
query: 中华人民共和国外国国家豁免法 适用与法理研究
kind: paper
score: 0.0
text_length: 51910
raw_file: null
harvested_at: '2026-08-17 17:29:49'
