title: 伍某與北京市懷柔區渤海鎮人民政府信息公開二審行政判決書 - 維基文庫，自由的圖書館
url: https://zh.wikisource.org/zh-hant/%E4%BC%8D%E6%9F%90%E4%B8%8E%E5%8C%97%E4%BA%AC%E5%B8%82%E6%80%80%E6%9F%94%E5%8C%BA%E6%B8%A4%E6%B5%B7%E9%95%87%E4%BA%BA%E6%B0%91%E6%94%BF%E5%BA%9C%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%E4%BA%8C%E5%AE%A1%E8%A1%8C%E6%94%BF%E5%88%A4%E5%86%B3%E4%B9%A6
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 政府信息公开 行政复议与行政诉讼 典型案例
kind: case
score: 0.0
text_length: 3547
raw_file: source.html
harvested_at: '2026-08-17 17:29:20'
