title: 【以案普法】女子怀孕后被调岗，月薪还从1.7万降至3千！_新闻资讯_企业动态_贵州诚合律师事务所
url: https://www.gzchlssws.com/gongsixinwen/9410.html
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 妇女权益保障法 职场性别平等 典型司法案例
kind: case
score: 0.19999999999999996
text_length: 2287
raw_file: source.html
harvested_at: '2026-08-17 17:29:38'
