title: “开盒”曝光他人信息被告人获刑 最高法发布典型案例从严惩治网暴 | 每经网
url: https://www.nbd.com.cn/articles/2026-03-03/4276478.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 最高人民法院 依法惩治网络暴力 典型案例
kind: case
score: 0.19999999999999996
text_length: 3043
raw_file: source.html
harvested_at: '2026-08-17 17:29:00'
