title: 指导案例237号-郎溪某服务外包有限公司诉徐某申确认劳动关系纠纷案 - 劳动法和指导案例 - 律法网
url: https://www.055110.com/ld/6/565.html
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 最高人民法院 新就业形态劳动者权益保障 典型案例
kind: case
score: 0.8
text_length: 2616
raw_file: source.html
harvested_at: '2026-08-17 17:29:13'
