title: 最高人民法院发布第42批指导性案例
url: http://qdzy.sdcourt.gov.cn/jinanzy/376209/376187/zdxal/37795882/index.html
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 最高人民法院 新就业形态劳动者权益保障 典型案例
kind: case
score: 0.19999999999999996
text_length: 10011
raw_file: null
harvested_at: '2026-08-17 17:29:27'
