title: 最高人民法院关于审理涉及农村土地承包纠纷案件适用法律问题的解释 - 维基文库，自由的图书馆
url: https://zh.wikisource.org/zh-hans/%E6%9C%80%E9%AB%98%E4%BA%BA%E6%B0%91%E6%B3%95%E9%99%A2%E5%85%B3%E4%BA%8E%E5%AE%A1%E7%90%86%E6%B6%89%E5%8F%8A%E5%86%9C%E6%9D%91%E5%9C%9F%E5%9C%B0%E6%89%BF%E5%8C%85%E7%BA%A0%E7%BA%B7%E6%A1%88%E4%BB%B6%E9%80%82%E7%94%A8%E6%B3%95%E5%BE%8B%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E9%87%8A
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 乡村振兴促进法 农村土地承包经营 典型纠纷案例
kind: case
score: 0.8
text_length: 4018
raw_file: null
harvested_at: '2026-08-17 17:29:13'
