title: 翟国强：合宪性审查中推进宪法解释的策略与方案-中国社会科学院大学法学院
url: https://law.ucass.edu.cn/info/1985/7607.htm
category_id: 08_宪法与国家机构
category_name: 宪法与国家治理法治专题
query: 合宪性审查 宪法解释 司法实践与学术论文
kind: paper
score: 0.19999999999999996
text_length: 10130
raw_file: null
harvested_at: '2026-08-17 17:30:03'
