title: '北京高院通报“东傲集团”电诈案：伪装“成功人士”诈骗百万 8人获刑

  _光明网'
url: https://share.gmw.cn/legal/2026-01/06/content_38521904.htm
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 最高人民检察院 依法惩治电信网络诈骗 典型案例
kind: case
score: 0.0
text_length: 4696
raw_file: null
harvested_at: '2026-08-17 17:28:58'
