title: 资料_36505
url: https://www.hshfy.sh.cn/shfy/web/flws2pdf.jsp?pa=adGFoPaOoMjAyNKOpu6Y3NMPx1tUxNDY4usUmd3N4aD0zJndzbGI9w%2FHKwsXQvvbK6QPdcssPdcssz
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 商业银行法 保险法 金融纠纷 典型裁判案例
kind: case
score: 0.19999999999999996
text_length: 20778
raw_file: source.pdf
harvested_at: '2026-08-17 17:29:03'
