title: 最高法判例：行政行为违法但不具有可撤销内容，针对的是事实行为
url: http://sdcourt.gov.cn/jnangxqfy/400112/400095/6863013/index.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 最高人民法院 行政诉讼 指导性案例 裁判要旨
kind: case
score: 0.0
text_length: 5819
raw_file: null
harvested_at: '2026-08-17 17:29:25'
