title: 指导案例185号：闫佳琳诉浙江喜来登度假村有限公司平等就业权纠纷案
url: http://lylsfy.sdcourt.gov.cn/jningjinxfy/385118/385119/9216794/index.html
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 妇女权益保障法 职场性别平等 典型司法案例
kind: case
score: 1.0
text_length: 2864
raw_file: source.html
harvested_at: '2026-08-17 17:29:28'
