title: 特大跨境电信诈骗案：每天从肯尼亚凌晨3点骗到北京下午4点|界面新闻 · 中国
url: https://www.jiemian.com/article/1833317.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 最高人民检察院 依法惩治电信网络诈骗 典型案例
kind: case
score: 0.19999999999999996
text_length: 4522
raw_file: source.html
harvested_at: '2026-08-17 17:28:44'
