title: 前研e案|虚拟偶像“人肉开盒”的侵权责任认定
url: https://m.thepaper.cn/newsDetail_forward_32554945
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 最高人民法院 人格权侵权典型案例 裁判要点
kind: case
score: 0.0
text_length: 8703
raw_file: source.html
harvested_at: '2026-08-17 17:28:46'
