title: 最高人民法院关于确定民事侵权精神损害赔偿责任若干问题的解释-北大法宝V6官网
url: https://www.pkulaw.com/chl/0322a21ba74de353bdfb.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 最高人民法院 人格权侵权典型案例 裁判要点
kind: case
score: 1.0
text_length: 2996
raw_file: source.html
harvested_at: '2026-08-17 17:28:36'
