title: 严冬峰：备案审查决定的出台背景和主要内容解读|关于|规章|规范性|合法性_网易订阅
url: https://www.163.com/dy/article/IO971IBR0530W1MT.html
category_id: 08_宪法与国家机构
category_name: 宪法与国家治理法治专题
query: 全国人大常委会 规范性文件备案审查 典型案例
kind: case
score: 0.19999999999999996
text_length: 22708
raw_file: source.html
harvested_at: '2026-08-17 17:30:04'
