title: 【以案釋法】孟某訴某單位駁回行政復議申請決定及行政賠償案-政策解讀-中華人民共和國交通運輸部
url: https://big5.mot.gov.cn/gate/big5/www.mot.gov.cn/gongkai/zcjd/202512/t20251226_4191479.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 政府信息公开 行政复议与行政诉讼 典型案例
kind: case
score: 0.19999999999999996
text_length: 1605
raw_file: null
harvested_at: '2026-08-17 17:29:17'
