title: 江苏响水废弃危化品特大爆炸安全事故一审宣判-成都理工大学国资与实验室管理处
url: https://gz.cdut.edu.cn/info/1041/1178.htm
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 安全生产法 危险化学品安全生产 事故责任典型案例
kind: case
score: 1.0
text_length: 2168
raw_file: null
harvested_at: '2026-08-17 17:29:24'
