title: （2017）最高法民辖终224号民事裁定书
url: https://www.lawbaike.com/zhishi/235367196.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 民法典侵权责任编 惩罚性赔偿 典型案例与法律适用
kind: case
score: 0.4
text_length: 8455
raw_file: null
harvested_at: '2026-08-17 17:28:41'
dir_name: （2017）最高法民辖终224号民事裁定书
rel_dir: references/01_民商法_民法典与公司法/（2017）最高法民辖终224号民事裁定书
