title: 刑法修正案（十二）3月1日起施行：重惩行贿犯罪 强化对民企保护_中国人大网
url: http://www.npc.gov.cn/npc/c2/c30834/202403/t20240301_434965.html
category_id: 02_刑法与刑事诉讼法
category_name: 刑法与刑事诉讼专题
query: 刑法修正案（十二） 行贿受贿一起查 典型案例
kind: case
score: 0.8
text_length: 6965
raw_file: source.html
harvested_at: '2026-08-17 17:28:51'
