title: 中华人民共和国行政处罚法(2021修订)
url: http://wjw.smx.gov.cn/505/615830400/883216.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政处罚法 处罚法定 过罚相当 典型案例
kind: case
score: 0.4
text_length: 11077
raw_file: source.html
harvested_at: '2026-08-17 17:29:12'
