title: 魏祖贤：创制性地方授权立法的授权路径与权限边界 ——以新《立法法》第84条为视角
url: https://www.legal-theory.org/index.php?mod=info&act=view&id=28056
category_id: 08_宪法与国家机构
category_name: 宪法与国家治理法治专题
query: 立法法修改 地方立法权限与协同立法 案例研究
kind: paper
score: 0.19999999999999996
text_length: 21159
raw_file: null
harvested_at: '2026-08-17 17:30:38'
