title: 《民法典》第1183条【精神损害赔偿】释论
url: https://www.jtsg.org/2022-05-22/8733.html
category_id: 01_民商法_民法典与公司法
category_name: 民商法与民法典专题
query: 民法典侵权责任编 惩罚性赔偿 典型案例与法律适用
kind: paper
score: 0.0
text_length: 11495
raw_file: source.html
harvested_at: '2026-08-17 17:28:44'
dir_name: 民法典第1183条精神损害赔偿释论
rel_dir: references/01_民商法_民法典与公司法/民法典第1183条精神损害赔偿释论
