title: 山东聊城“5·1”重大爆炸着火事故调查报告发布，5人被追究刑责|川观新闻
url: https://cbgc.scol.com.cn/news/4926292
category_id: 05_社会法与劳动保障
category_name: 社会法与劳动权益专题
query: 安全生产法 危险化学品安全生产 事故责任典型案例
kind: case
score: 0.8
text_length: 6701
raw_file: source.html
harvested_at: '2026-08-17 17:29:26'
