title: 土地互换后，承包户多耕种部分的土地承包经营权争议，不属于法院受理范围 - 农村土地 - 农村宅基地及房屋 - 北京房地产律师网
url: http://yingke010.com/article/11234.html
category_id: 03_经济法与财税金融
category_name: 经济法与金融监管专题
query: 乡村振兴促进法 农村土地承包经营 典型纠纷案例
kind: case
score: 0.0
text_length: 4785
raw_file: null
harvested_at: '2026-08-17 17:29:31'
