title: 司法院釋字第751號解釋 - 维基文库，自由的图书馆
url: https://zh.wikisource.org/wiki/%E5%8F%B8%E6%B3%95%E9%99%A2%E9%87%8B%E5%AD%97%E7%AC%AC751%E8%99%9F%E8%A7%A3%E9%87%8B
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政处罚法 处罚法定 过罚相当 典型案例
kind: case
score: 0.0
text_length: 8070
raw_file: source.html
harvested_at: '2026-08-17 17:29:19'
