title: 行政处罚自由裁量权是什么（自由裁量合理使用的案例）_法外狂徒
url: https://www.chuangxiangniao.com/law/274391.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政处罚法 处罚法定 过罚相当 典型案例
kind: case
score: 1.0
text_length: 16729
raw_file: source.html
harvested_at: '2026-08-17 17:29:08'
