title: 最高法典型案例：行政协议案件中存在显失公平或不当联结的审查处理
url: http://jnangxqfy.sdcourt.gov.cn/jnangxqfy/400112/400095/13955194/index.html
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 行政协议履行与解除 行政诉讼典型案例
kind: case
score: 0.4
text_length: 3639
raw_file: source.html
harvested_at: '2026-08-17 17:29:04'
