title: 国家赔偿中的“相应”精神损害抚慰金_明德公法网
url: http://calaw.ruc.edu.cn/gfal/xzfalfx/75ab4c37338f472eadd2b032c9df8205.htm
category_id: 04_行政法与国家赔偿
category_name: 行政法与行政诉讼专题
query: 国家赔偿法 刑事赔偿 行政赔偿 典型案例
kind: case
score: 0.6
text_length: 14578
raw_file: source.html
harvested_at: '2026-08-17 17:29:20'
